discussion_show:
    path: /show/{slug}
    defaults: { _controller: 'App:Discussion:show'}

discussion_add_global:
    path: /addglobal
    defaults: { _controller: 'App:Discussion:addGlobal' }

discussion_add_theme:
    path: /addtheme/{slug}
    defaults: { _controller: 'App:Discussion:addTheme' }

discussion_add_proposal:
    path: /addproposal/{slug}
    defaults: { _controller: 'App:Discussion:addProposal' }

discussion_add_private:
    path: /addprivate
    defaults: { _controller: 'App:Discussion:addPrivate' }

discussion_edit:
    path: /edit/{slug}
    defaults: { _controller: 'App:Discussion:edit' }

discussion_add_private_member:
    path: /addprivatemember/{slug}
    defaults: { _controller: 'App:Discussion:addPrivateMember' }

discussion_remove_private_member:
    path: /removeprivatemember/{discussionSlug}/{privateMemberId}
    defaults: { _controller: 'App:Discussion:removePrivateMember' }

discussion_change_admin:
    path: /changeadmin/{slug}
    defaults: { _controller: 'App:Discussion:changeAdmin' }

discussion_delete:
    path: /delete/{slug}
    defaults: { _controller: 'App:Discussion:delete' }

discussion_move_to_global:
    path: /movetoglobal/{slug}
    defaults: { _controller: 'App:Discussion:moveToGlobal' }

discussion_move_to_theme:
    path: /movetotheme/{slug}
    defaults: { _controller: 'App:Discussion:moveToTheme' }

discussion_move_to_proposal:
    path: /movetoproposal/{slug}
    defaults: { _controller: 'App:Discussion:moveToProposal' }
