message_show:
    path: /show/{slug}
    defaults: { _controller: 'App:Message:show'}

message_send:
    path: /send
    defaults: { _controller: 'App:Message:send'}

message_reply:
    path: /reply/{slug}
    defaults: { _controller: 'App:Message:reply'}