old_proposal_show:
    path: /show/{slug}
    defaults: { _controller: 'App:OldProposal:show'}

old_proposal_next_version:
    path: /next_version/{slug}
    defaults: { _controller: 'App:OldProposal:nextVersion'}

old_proposal_previous_version:
    path: /previous_version/{slug}
    defaults: { _controller: 'App:OldProposal:previousVersion'}
