post_open_private_discussion:
    path: /open_private_discussion/{id}
    defaults: { _controller: 'App:Post:openPrivateDiscussion' }

post_move:
    path: /move/{id}
    defaults: { _controller: 'App:Post:move' }

post_delete:
    path: /delete/{id}
    defaults: { _controller: 'App:Post:delete' }
