private_discussion_show:
    path: /show/{slug}
    defaults: { _controller: 'App:PrivateDiscussion:show'}

private_discussion_edit:
    path: /edit/{slug}
    defaults: { _controller: 'App:PrivateDiscussion:edit' }

private_discussion_lock:
    path: /lock/{slug}
    defaults: { _controller: 'App:PrivateDiscussion:lock' }
