proposaldraft_show:
    path: /show/{slug}
    defaults: { _controller: 'App:ProposalDraft:show'}

proposaldraft_add:
    path: /add
    defaults: { _controller: 'App:ProposalDraft:add' }

proposaldraft_delete:
    path: /delete/{slug}
    defaults: { _controller: 'App:ProposalDraft:delete' }

proposaldraft_edit:
    path: /edit/{slug}
    defaults: { _controller: 'App:ProposalDraft:edit' }

proposaldraft_publish:
    path: /publish/{slug}
    defaults: { _controller: 'App:ProposalDraft:publish' }

proposaldraft_removesideauthor:
    path: /removesideauthor/{slug}
    defaults: { _controller: 'App:ProposalDraft:removeSideAuthor' }
