proposal_version_show:
    path: /show/{slug}
    defaults: { _controller: 'App:ProposalVersion:show'}

proposal_version_next_version:
    path: /next_version/{slug}
    defaults: { _controller: 'App:ProposalVersion:nextVersion'}

proposal_version_previous_version:
    path: /previous_version/{slug}
    defaults: { _controller: 'App:ProposalVersion:previousVersion'}
