dl-deploy-preprod:
    stage: preprod
    host: dl-deploy-preprod
    deploy_path: /var/www/dl3.org
    branch: develop

dl-deploy-prod:
    stage: prod
    host: dl-deploy-prod
    deploy_path: /var/www/dl4
    branch: master

dl-deploy-test:
    stage: test
    host: dl-deploy-test
    deploy_path: /var/www/dl3.org
    branch: develop

dl-deploy-preprod-patch:
    stage: preprod
    host: dl-deploy-preprod
    deploy_path: /var/www/dl3.org
    branch: patch
