dl-deploy-preprod:
    stage: preprod
    host: dl-deploy-preprod
    deploy_path: /var/www/dl3.org
    branch: deployer

dl-deploy-prod:
    stage: prod
    host: dl-deploy-prod
    deploy_path: /var/www/dl3.org
    branch: master

