imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:       ~
    translator: { fallback: "%locale%" }
    secret:     "%secret%"
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:       "%locale%"
    trusted_hosts:        ~
    session:              ~
    fragments:            ~
    http_method_override: true
    assets:               ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
            default_table_options:
                charset: utf8mb4
                collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            tree: true
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

beelab_recaptcha2:
    site_key: '%google_recaptcha.site_key%'
    secret: '%google_recaptcha.secret%'
